name: Deploy to Hetzner Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and run Docker container
        run: |
          cd /opt/myapp || git clone git@github.com:Kdaniel-prog/trading.bot.git /opt/myapp && cd /opt/myapp
          git pull
          docker stop springapp_container || true
          docker rm springapp_container || true
          docker build -t springapp .
          docker run -d -p 8080:8080 --name springapp_container springapp
          echo "==== Last 20 log lines from app ===="
          docker logs --tail 20 springapp_container
          echo "🚀 Deploy successful!"
